- Apps:
    - Vaultwarden:
        icon: bitwarden.png
        href: https://home-server.tailee5654.ts.net:8222
        description: Password manager
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://home-server.tailee5654.ts.net:8443
        description: Uptime status checks
        widget:
          type: uptimekuma
          url: http://127.0.0.1:3001
          slug: homelab
